// Download WOFF2 font files for IBM Plex Sans, IBM Plex Mono, and Outfit from Google Fonts
// and emit a self-hosted @font-face stylesheet at css/fonts.css.
//
// Latin subset only — enough for an English site and keeps the payload small.
//
// Usage: node scripts/fetch-fonts.js

const fs = require('fs');
const path = require('path');
const https = require('https');

const root = path.resolve(__dirname, '..');
const fontsDir = path.join(root, 'fonts');
const cssOut = path.join(root, 'css', 'fonts.css');

if (!fs.existsSync(fontsDir)) fs.mkdirSync(fontsDir, { recursive: true });

const GOOGLE_CSS_URL =
    'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&family=Outfit:wght@400;500;600;700&display=swap';

// A modern Chrome UA so Google serves WOFF2 + unicode-range subsets.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36';

function fetch(url, headers = {}) {
    return new Promise((resolve, reject) => {
        https
            .get(url, { headers: { 'User-Agent': UA, ...headers } }, (res) => {
                if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
                    return resolve(fetch(res.headers.location, headers));
                }
                if (res.statusCode !== 200) {
                    return reject(new Error('HTTP ' + res.statusCode + ' for ' + url));
                }
                const chunks = [];
                res.on('data', (c) => chunks.push(c));
                res.on('end', () => resolve(Buffer.concat(chunks)));
                res.on('error', reject);
            })
            .on('error', reject);
    });
}

function slugify(s) {
    return s.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
}

(async () => {
    console.log('Fetching Google Fonts CSS …');
    const cssBuf = await fetch(GOOGLE_CSS_URL);
    const cssRaw = cssBuf.toString('utf8');

    // Parse @font-face blocks
    const blocks = [...cssRaw.matchAll(/\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/gi)];
    console.log('Found', blocks.length, '@font-face blocks');

    const outRules = [];
    const downloads = new Map();

    for (const [, subset, body] of blocks) {
        if (subset !== 'latin') continue; // English-only — drop other subsets

        const family = (body.match(/font-family:\s*['"]([^'"]+)['"]/) || [])[1];
        const weight = (body.match(/font-weight:\s*(\d+)/) || [])[1];
        const style = (body.match(/font-style:\s*([a-z]+)/) || [])[1] || 'normal';
        const urlMatch = body.match(/url\(([^)]+)\)\s+format\(['"]woff2['"]\)/);
        const range = (body.match(/unicode-range:\s*([^;]+);/) || [])[1];

        if (!family || !urlMatch) continue;
        const remote = urlMatch[1].replace(/^['"]|['"]$/g, '');
        const filename = slugify(family) + '-' + weight + (style === 'italic' ? 'i' : '') + '.woff2';
        const local = '/fonts/' + filename;

        downloads.set(filename, remote);

        outRules.push(
            '@font-face {\n' +
                "    font-family: '" + family + "';\n" +
                '    font-style: ' + style + ';\n' +
                '    font-weight: ' + weight + ';\n' +
                '    font-display: swap;\n' +
                "    src: url('" + local + "') format('woff2');\n" +
                (range ? '    unicode-range: ' + range + ';\n' : '') +
                '}'
        );
    }

    console.log('Downloading', downloads.size, 'WOFF2 files …');
    let total = 0;
    for (const [filename, url] of downloads) {
        const data = await fetch(url);
        fs.writeFileSync(path.join(fontsDir, filename), data);
        total += data.length;
        console.log('  ', filename, '(' + Math.round(data.length / 1024) + ' KB)');
    }

    const header =
        '/* Self-hosted IBM Plex Sans + IBM Plex Mono + Outfit (latin only).\n' +
        '   Generated by scripts/fetch-fonts.js — do not edit by hand. */\n\n';
    fs.writeFileSync(cssOut, header + outRules.join('\n\n') + '\n', 'utf8');
    console.log('Wrote', cssOut, '(' + outRules.length + ' faces, ' + Math.round(total / 1024) + ' KB total)');
})();
